[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = ['ruby']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_done_update = "runtime! rc/plugin-vim-javascript.vim"

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']
build = 'make'

# [[plugins]]
# repo = 'aklt/plantuml-syntax'
# on_ft = ['uml','plantuml']
